import 'package:flutter/material.dart';

class CustomTable extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: [
          // Title and Logos Section with background color and padding
          Container(
            color: Colors.blueAccent.shade100, // Background color for the title section
            padding: EdgeInsets.symmetric(vertical: 20.0, horizontal: 16.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Image.asset('assets/images/logoa.png', width: 50, height: 50), // Left logo
                Expanded(
                  child: Center(
                    child: Text(
                      'Report Title', // Title
                      style: TextStyle(
                        fontSize: 32,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
                Image.asset('assets/images/logoa.png', width: 50, height: 50), // Right logo
              ],
            ),
          ),

          SizedBox(height: 20),

          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildKeyValueRow('Date', '13th January 2025'),
                _buildKeyValueRow('Generated by', 'John Doe'),
                _buildKeyValueRow('Report ID', 'ABC123456'),
                SizedBox(height: 20),
              ],
            ),
          ),

          // Table Section
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Table(
              border: TableBorder.all(color: Colors.grey, width: 1),
              columnWidths: {
                0: FixedColumnWidth(50), // Serial number column width
                for (int i = 1; i < 10; i++) i: FixedColumnWidth(150), // Set fixed width for other columns
              },
              children: [
                // Header Row
                TableRow(
                  decoration: BoxDecoration(
                    color: Colors.blueAccent.shade200, // Header row background color
                  ),
                  children: [
                    _buildTableHeaderCell('No.'),
                    ...List.generate(9, (index) {
                      return _buildTableHeaderCell('Column ${index + 1}');
                    }),
                  ],
                ),

                // Data Rows with Serial Numbers
                for (int row = 1; row <= 4; row++)
                  TableRow(
                    decoration: BoxDecoration(
                      color: row % 2 == 0
                          ? Colors.blueGrey.shade50 // Alternate row colors
                          : Colors.white,
                    ),
                    children: [
                      _buildTableCell('$row'), // Serial number for the row
                      ...List.generate(9, (index) {
                        return _buildTableCell('Row $row, Data ${index + 1}');
                      }),
                    ],
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // Helper method to build key-value rows
  Widget _buildKeyValueRow(String key, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            key,
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
          ),
          Text(
            value,
            style: TextStyle(fontSize: 16),
          ),
        ],
      ),
    );
  }

  // Helper method to build table header cells
  Widget _buildTableHeaderCell(String text) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Text(
        text,
        style: TextStyle(
          fontWeight: FontWeight.bold,
          fontSize: 16,
          color: Colors.white,
        ),
        textAlign: TextAlign.center,
      ),
    );
  }

  // Helper method to build table data cells
  Widget _buildTableCell(String text) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Text(
        text,
        style: TextStyle(fontSize: 14),
        textAlign: TextAlign.center,
      ),
    );
  }
}
